<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Time at WorkNot Punched In0h 0m TodayTh_4aaad9</name>
   <tag></tag>
   <elementGuidId>5c84fe27-69e4-44e4-8b9a-ec54a08c984a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.oxd-layout-context</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0d455c7e-965f-48df-9991-1338cd15731a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-layout-context</value>
      <webElementGuid>3ab50ecc-8def-46ce-80c5-010f82e20f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Time at WorkNot Punched In0h 0m TodayThis WeekDec 12 - Dec 180h 0m My ActionsNo Pending Actions to PerformQuick LaunchEmployees on Leave TodayLeave Period Not DefinedEmployee Distribution by Sub UnitEmployee Distribution by Location</value>
      <webElementGuid>bf59126a-78b0-4404-ba96-518c756c77ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]</value>
      <webElementGuid>d21cfbfa-03ac-4a19-90e8-cfc80b9bfddd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]</value>
      <webElementGuid>191a0b10-1bb3-487b-b5cb-f8e603a6ac7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OrangeHRM, Inc'])[1]/preceding::div[46]</value>
      <webElementGuid>8f4781af-e2ba-4acb-b671-d17fd63ffe8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]</value>
      <webElementGuid>529df71c-ff7f-4d6a-9a04-d4ee8fdb9278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Time at WorkNot Punched In0h 0m TodayThis WeekDec 12 - Dec 180h 0m My ActionsNo Pending Actions to PerformQuick LaunchEmployees on Leave TodayLeave Period Not DefinedEmployee Distribution by Sub UnitEmployee Distribution by Location' or . = 'Time at WorkNot Punched In0h 0m TodayThis WeekDec 12 - Dec 180h 0m My ActionsNo Pending Actions to PerformQuick LaunchEmployees on Leave TodayLeave Period Not DefinedEmployee Distribution by Sub UnitEmployee Distribution by Location')]</value>
      <webElementGuid>c74f0949-24e3-469b-9e2e-d20781c9e959</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
