<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Edit VacancyVacancy NameJob TitleQA Eng_99b0dc</name>
   <tag></tag>
   <elementGuidId>be7aa881-e10e-42a0-9c64-f637074ca75c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.oxd-layout-context</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6b0859e0-548b-42ad-b947-e9c4926121f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-layout-context</value>
      <webElementGuid>447c721d-3cf2-43d3-8248-69ea28bc37fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit VacancyVacancy NameJob TitleQA EngineerDescriptionHiring ManagerNumber of PositionsActivePublish in RSS Feed and Web PageRSS Feed URL : http://localhost:8181/web/index.php/recruitmentApply/jobs.rssWeb Page URL : http://localhost:8181/web/index.php/recruitmentApply/jobs.html * Required Cancel  Save Attachments Add No Records FoundFile NameFile SizeFile TypeCommentActions</value>
      <webElementGuid>47616703-981b-4cde-b839-c437bce115e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]</value>
      <webElementGuid>91eb9bed-89fc-4752-92f6-a7d1617e81c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]</value>
      <webElementGuid>aa08143e-2f25-4438-906f-d2ecbd3e4e96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]</value>
      <webElementGuid>c09d2a89-9b1f-47d0-bb72-6e3f61194307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Edit VacancyVacancy NameJob TitleQA EngineerDescriptionHiring ManagerNumber of PositionsActivePublish in RSS Feed and Web PageRSS Feed URL : http://localhost:8181/web/index.php/recruitmentApply/jobs.rssWeb Page URL : http://localhost:8181/web/index.php/recruitmentApply/jobs.html * Required Cancel  Save Attachments Add No Records FoundFile NameFile SizeFile TypeCommentActions' or . = 'Edit VacancyVacancy NameJob TitleQA EngineerDescriptionHiring ManagerNumber of PositionsActivePublish in RSS Feed and Web PageRSS Feed URL : http://localhost:8181/web/index.php/recruitmentApply/jobs.rssWeb Page URL : http://localhost:8181/web/index.php/recruitmentApply/jobs.html * Required Cancel  Save Attachments Add No Records FoundFile NameFile SizeFile TypeCommentActions')]</value>
      <webElementGuid>b1fb31e0-0e75-44bc-bfe2-638454d776cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
